// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJH_CkyqHRYBEhUGWfMXPcJAQehdgzV-c',
    appId: '1:659685263609:web:47a68333edba67affb7a28',
    messagingSenderId: '659685263609',
    projectId: 'financeapasg',
    authDomain: 'financeapasg.firebaseapp.com',
    storageBucket: 'financeapasg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJCrHKusPXZ2ZIqZU-bUKEvBCWVhoofKI',
    appId: '1:659685263609:android:9bd8fe045873dfb9fb7a28',
    messagingSenderId: '659685263609',
    projectId: 'financeapasg',
    storageBucket: 'financeapasg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlfBzTnCoyq7sRyrZdlNllS51IyXVhCQQ',
    appId: '1:659685263609:ios:1389bad18fcc3609fb7a28',
    messagingSenderId: '659685263609',
    projectId: 'financeapasg',
    storageBucket: 'financeapasg.appspot.com',
    iosBundleId: 'com.example.financeApAsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlfBzTnCoyq7sRyrZdlNllS51IyXVhCQQ',
    appId: '1:659685263609:ios:bab715d93e5cd69ffb7a28',
    messagingSenderId: '659685263609',
    projectId: 'financeapasg',
    storageBucket: 'financeapasg.appspot.com',
    iosBundleId: 'com.example.financeApAsg.RunnerTests',
  );
}
